# Generated by Django 5.0.2 on 2024-09-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='text_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='member',
            name='fullname_en',
            field=models.CharField(max_length=255, null=True, verbose_name='fullname'),
        ),
        migrations.AddField(
            model_name='member',
            name='fullname_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='fullname'),
        ),
        migrations.AddField(
            model_name='member',
            name='fullname_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='fullname'),
        ),
        migrations.AddField(
            model_name='member',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='member',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='member',
            name='position_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
